# Server settings
server:
  port: 8089
spring:
  application:
    name: news-portal
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
  datasource:
    url: jdbc:postgresql://localhost:5433/news-portal-db
    username: news-portal
    password: pWiUuHyyb3Wl
  liquibase:
    change-log: classpath:/db/changelog.xml
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
        expiration: 604800000