CREATE TABLE private.source
(
    id   VARCHAR(255),
    name VARCHAR(255),
    url  VARCHAR(255),
    CONSTRAINT pk_source PRIMARY KEY (id)
);

CREATE TABLE private.topic
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    CONSTRAINT pk_topic PRIMARY KEY (id)
);

CREATE TABLE private.news
(
    id           UUID NOT NULL,
    title        VARCHAR(255),
    content      VARCHAR(255),
    description  VARCHAR(255),
    author       VARCHAR(255),
    url          VARCHAR(255),
    url_to_image VARCHAR(255),
    source_id    VARCHAR(255),
    published_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_news PRIMARY KEY (id)
);

CREATE TABLE private.news_topic
(
    news_id  UUID   NOT NULL,
    topic_id BIGINT NOT NULL
);

ALTER TABLE private.news
    ADD CONSTRAINT fk_news_on_source FOREIGN KEY (source_id) REFERENCES private.source (id);

ALTER TABLE private.news_topic
    ADD CONSTRAINT fk_news_on_topic FOREIGN KEY (news_id) REFERENCES private.news (id);

ALTER TABLE private.news_topic
    ADD CONSTRAINT fk_topic_on_news FOREIGN KEY (topic_id) REFERENCES private.topic (id);