CREATE SCHEMA private;

CREATE TABLE private.role
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code        VARCHAR(15)                             NOT NULL,
    description VARCHAR(255),
    CONSTRAINT pk_role PRIMARY KEY (id)
);


CREATE TABLE private.role_user
(
    role_id BIGINT NOT NULL,
    user_id UUID   NOT NULL
);

CREATE TABLE private.user
(
    id                      UUID         NOT NULL,
    username                VARCHAR(255) NOT NULL,
    firstname               VARCHAR(255),
    lastname                VARCHAR(255),
    email                   VARCHAR(255) NOT NULL,
    password                VARCHAR(255),
    enabled                 BOOLEAN,
    account_non_expired     BOOLEAN,
    credentials_non_expired BOOLEAN,
    account_non_locked      BOOLEAN,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE private.user
    ADD CONSTRAINT uc_user_email UNIQUE (email);

ALTER TABLE private.user
    ADD CONSTRAINT uc_user_username UNIQUE (username);

ALTER TABLE private.role_user
    ADD CONSTRAINT fk_role_user_on_role FOREIGN KEY (role_id) REFERENCES private.role (id);

ALTER TABLE private.role_user
    ADD CONSTRAINT fk_role_user_on_user FOREIGN KEY (user_id) REFERENCES private.user (id);

CREATE TABLE private.token
(
    id         UUID    NOT NULL,
    token      VARCHAR(255),
    token_type VARCHAR(255),
    revoked    BOOLEAN NOT NULL,
    expired    BOOLEAN NOT NULL,
    user_id    UUID,
    CONSTRAINT pk_token PRIMARY KEY (id)
);

ALTER TABLE private.token
    ADD CONSTRAINT uc_token_token UNIQUE (token);

ALTER TABLE private.token
    ADD CONSTRAINT FK_TOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES private.user (id);